variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  VERSION: 2.0.3

stages:
  - build_xdlp4710_20um
  - build_xdlp4710
  - build_dlp4710
  - build_xbase
  - build_base


build_base:
  stage: build_base
  script:
    - rm -rf packaging
    - bash change-version-number.sh -t base ${VERSION}
    - bash make-deb-package.sh release
    - bash make-deb-package.sh debug
  tags:
    - lightfield
  artifacts:
    paths:
      - packaging

build_xbase:
  stage: build_xbase
  script:
    - rm -rf packaging
    - bash change-version-number.sh -t xbase ${VERSION}
    - bash make-deb-package.sh release
    - bash make-deb-package.sh debug
  tags:
    - lightfield
  artifacts:
    paths:
      - packaging

build_dlp4710:
  stage: build_dlp4710
  script:
    - rm -rf packaging
    - bash change-version-number.sh -t dlp4710 ${VERSION}
    - bash make-deb-package.sh release
    - bash make-deb-package.sh debug
  tags:
    - lightfield
  artifacts:
    paths:
      - packaging

build_xdlp4710:
  stage: build_xdlp4710
  script:
    - rm -rf packaging
    - bash change-version-number.sh -t xdlp4710 ${VERSION}
    - bash make-deb-package.sh release
    - bash make-deb-package.sh debug
  tags:
    - lightfield
  artifacts:
    paths:
      - packaging

build_xdlp4710_20um:
  stage: build_xdlp4710_20um
  script:
    - rm -rf packaging
    - bash change-version-number.sh -t xdlp4710-20um ${VERSION}
    - bash make-deb-package.sh release
    - bash make-deb-package.sh debug
  tags:
    - lightfield
  artifacts:
    paths:
      - packaging
