variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build:
  stage: build
  script:
    - rm -rf packaging
    - bash make-deb-package.sh release
  tags:
    - lightfield
  artifacts:
    paths:
      - packaging
