variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build:
  stage: build
  before_script:
    - sudo rm -rf build mountmon/build packaging
  script:
    - sudo bash make-deb-package.sh release
  tags:
    - lightfield
